name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker buildx build --platform linux/amd64 -t us-west1-docker.pkg.dev/mariakhomenko-cdks2/amethyst-dev/gcp-training-javascript . --file Dockerfile --tag amethyst-dev:$(date +%s)

    - uses: actions/setup-node@v4
    - name: Run tests
      run: npm run test

    - name: Run lint
      run: npm run lint
